name: "Auto Test"

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Cangjie & Run Tests
      run: |
        # 1. 下载并解压 Cangjie 编译器
        wget "https://cangjie-lang.cn/v1/files/auth/downLoad?nsId=142267&fileName=Cangjie-0.53.13-linux_x64.tar.gz&objectKey=6719f1eb3af6947e3c6af327" -q -O Cangj
        tar -xzf Cangjie-0.53.13-linux_x64.tar.gz

        # 2. 配置环境变量 (注意点号和路径前的空格)
        . $GITHUB_WORKSPACE/cangjie/envsetup.sh

        # 3. 执行编译和测试命令
        cjc --version
        cd repo_workspace
        cjpm update
        cjpm build
        cjpm test
